version: 2.1
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
    

      
